"""Editor package."""

from epubforge.editor.apply import ApplyError, ApplyResult, apply_envelope, apply_log
from epubforge.editor.ops import (
    BlockSnapshot,
    CompactMarker,
    DeleteBlock,
    EditOp,
    FootnoteOp,
    HeadingSpec,
    InsertBlock,
    MergeBlocks,
    MergeChapters,
    NoopOp,
    OpEnvelope,
    Precondition,
    RelocateBlock,
    RevertOp,
    SetFootnoteFlag,
    SetHeadingId,
    SetHeadingLevel,
    SetRole,
    SetStyleClass,
    SetText,
    SplitBlock,
    SplitChapter,
)

__all__ = [
    "BlockSnapshot",
    "CompactMarker",
    "DeleteBlock",
    "EditOp",
    "FootnoteOp",
    "ApplyError",
    "ApplyResult",
    "HeadingSpec",
    "InsertBlock",
    "MergeBlocks",
    "MergeChapters",
    "NoopOp",
    "OpEnvelope",
    "Precondition",
    "RelocateBlock",
    "RevertOp",
    "SetFootnoteFlag",
    "SetHeadingId",
    "SetHeadingLevel",
    "SetRole",
    "SetStyleClass",
    "SetText",
    "SplitBlock",
    "SplitChapter",
    "apply_envelope",
    "apply_log",
]
