"""Editor package public API for the AgentOutput/BookPatch workflow."""

from epubforge.editor.agent_output import AgentOutput, StageResult, SubmitResult
from epubforge.editor.doctor import (
    DoctorDelta,
    DoctorReport,
    Hint,
    ReadinessChecklist,
    build_doctor_report,
    compute_doctor_delta,
    evaluate_convergence,
)
from epubforge.editor.diff import DiffError, diff_books
from epubforge.editor.log import (
    AuditLogEntry,
    append_audit_event,
    compact_log,
    read_current_log,
)
from epubforge.editor.memory import (
    ChapterStatus,
    ConventionNote,
    EditMemory,
    MemoryHistoryEntry,
    MemoryMergeDecision,
    MemoryMergeResult,
    MemoryPatch,
    OpenQuestion,
    PatternNote,
    canonical_convention_key,
    canonical_pattern_key,
    merge_edit_memory,
)
from epubforge.editor.patch_commands import (
    PatchCommand,
    PatchCommandError,
    compile_patch_commands,
)
from epubforge.editor.patches import (
    BookPatch,
    DeleteNodeChange,
    InsertNodeChange,
    MoveNodeChange,
    PatchError,
    PatchScope,
    ReplaceNodeChange,
    SetFieldChange,
    apply_book_patch,
    validate_book_patch,
)
from epubforge.editor.projection import (
    render_chapter_projection,
    render_index,
)
from epubforge.editor.workspace import (
    GCResult,
    GitError,
    WorktreeCreateResult,
    WorktreeInfo,
    WorktreeRemoveResult,
    create_worktree,
    find_repo_root,
    gc_worktrees,
    list_worktrees,
    remove_worktree,
)

__all__ = [
    "AgentOutput",
    "AuditLogEntry",
    "BookPatch",
    "ChapterStatus",
    "ConventionNote",
    "DeleteNodeChange",
    "DiffError",
    "DoctorDelta",
    "DoctorReport",
    "EditMemory",
    "Hint",
    "InsertNodeChange",
    "MemoryHistoryEntry",
    "MemoryMergeDecision",
    "MemoryMergeResult",
    "MemoryPatch",
    "MoveNodeChange",
    "OpenQuestion",
    "PatchCommand",
    "PatchCommandError",
    "PatchError",
    "PatchScope",
    "PatternNote",
    "ReadinessChecklist",
    "ReplaceNodeChange",
    "SetFieldChange",
    "StageResult",
    "SubmitResult",
    "append_audit_event",
    "apply_book_patch",
    "build_doctor_report",
    "canonical_convention_key",
    "canonical_pattern_key",
    "compact_log",
    "compile_patch_commands",
    "compute_doctor_delta",
    "evaluate_convergence",
    "diff_books",
    "create_worktree",
    "find_repo_root",
    "gc_worktrees",
    "list_worktrees",
    "merge_edit_memory",
    "read_current_log",
    "render_chapter_projection",
    "render_index",
    "validate_book_patch",
    "remove_worktree",
    "GCResult",
    "GitError",
    "WorktreeCreateResult",
    "WorktreeInfo",
    "WorktreeRemoveResult",
]
